export const initAuthUserState = {
  isAuth: false,
  isAdmin: false,
  user: {
    _id: '',
    role: 'user',
    isVerified: false,
    isPlayer: false,
    position: '',
    isCaptain: false,
    image: { url: '', public_id: 0 },
    appsTarget: 0,
    goalsTarget: 0,
    assistsTarget: 0,
    name: '',
    email: '',
    matchesPlayed: [],
    createdAt: '',
    updatedAt: '',
    description: '',
    squadNumber: 0,
    yearJoined: '',
    canEdit: {
      details: false,
      photo: false,
      targets: false,
    },
  },
};
