export const link_text = {
  results: 'Results',
  results_stats: 'Results Stats',
  squad: 'Squad',
  squad_stats: 'Squad Stats',
  team: 'Team',
  about: 'About',
  home: 'Home',
  admin: 'Admin',
  sign_out: 'Sign out',
  sign_in: 'Sign in',
  add_result: 'Add Result',
  edit_result: 'Edit Result',
  users: 'Users',
  set_permissions: 'Set Permissions',
  team_details: 'Team Details',
  team_photo: 'Team Photo',
  trophies: 'Trophies',
  hall_of_fame: 'Hall of Fame',
  previous_seasons: 'Previous Seasons',
};
