export const page_headers = {
  // Main Views
  ABOUT: 'About',
  NOT_FOUND: 'Page not found',
  RESULTS_LIST: 'Results',
  RESULT_DETAILS: 'Result Details',
  RESULTS_STATS: 'Results Stats',
  SQUAD_LIST: 'Squad',
  PLAYER: 'Player Details',
  SQUAD_STATS: 'Squad Stats',
  TEAM: 'The Team',
  // Profile & Registration
  CHANGE_PASSWORD: 'Change Password',
  EDIT_ACCOUNT: 'Edit Account',
  EDIT_PLAYER_INFO: 'Edit Player Info',
  EDIT_TARGETS: 'Edit Targets',
  EDIT_USER_IMAGE: 'Set Photo',
  USER_PROFILE: 'Profile',
  FORGOT_PASSWORD: 'Forgot Password',
  RESET_PASSWORD: 'Reset Password',
  VALIDATED_EMAIL: '',
  // Admin Views
  ADMIN: 'Admin',
  ADMIN_RESULTS: 'Results Admin',
  ADMIN_TROPHIES: 'Trophies Admin',
  ADMIN_HOF: 'Hall of Fame Admin',
  ADMIN_SEASON: 'Previous Seasons Admin',
  ADMIN_USERS: 'Users Admin',
  // Admin Form Pages
  ADD_TEAM: 'Add Team',
  ADD_RESULT: 'Add Result',
  ADD_MATCH_PLAYER: 'Add Match Player',
  ADD_TROPHY: 'Add Trophy',
  ADD_SEASON: 'Add Season',
  ADD_AWARD: 'Add Award',
  ADD_HOF: 'Add Hall of Fame',
  EDIT_SEASON: 'Edit Previous Season',
  EDIT_RESULT: 'Edit Result',
  EDIT_HOF: 'Edit Hall of Fame',
  EDIT_TEAM: 'Edit Team Details',
  EDIT_TEAM_PHOTO: 'Edit Team Photo',
  EDIT_USER_PERMISSIONS: 'Edit User Permissions',
};
